name = "Custom"
license = "MIT"
licenselink = "https://github.com/nakamura196"
description = "Custom Hugo theme with Tailwind CSS"
tags = ["blog", "tailwind", "responsive", "dark", "light"]
features = ["dark mode", "multilingual", "search"]
min_version = "0.157.0"

[author]
name = "Nakamura"
